# Generated by Django 4.1.6 on 2023-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_region_country_area_country_capital_country_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
