# Generated by Django 4.1.6 on 2023-02-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='area',
            field=models.IntegerField(default=1),
        ),
    ]
