# Generated by Django 4.1.6 on 2023-02-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_country_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.DeleteModel(
            name='Capital',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
