# Generated by Django 4.1.6 on 2023-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_alter_country_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(default='None', max_length=60, null=True),
        ),
    ]
