# Generated by Django 4.1.6 on 2023-02-16 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_alter_country_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
